logging:
  level:
    pdtg: debug
server:
  port: 8081
pdtg:
  brewery:
    beerServiceHost: http://localhost:8080
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: true
  artemis:
    user: artemis
    password: simetraehcapa
